In [1]:
import numpy as np

#### Q1
##### array([[0., 0., 0., 0.],
#####   [0., 0., 0., 0.],
#####   [0., 0., 0., 0.]])
##### shape: (3, 4)

In [31]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### Q2
##### output 
##### array([3, 14,  7, 21,  9])

In [29]:
np.array([3, 14,  7, 21,  9])

array([ 3, 14,  7, 21,  9])

#### Q3
###### Create a random float array of this exact shape. Your values will differ — that is expected!
##### array([[0.37, 0.95, 0.73],
#####       [0.60, 0.16, 0.06],
#####       [0.84, 0.22, 0.48]])

In [46]:
np.random.seed(42) 
np.round(np.random.random((3,3)),2)


array([[0.37, 0.95, 0.73],
       [0.6 , 0.16, 0.16],
       [0.06, 0.87, 0.6 ]])

#### Q4
##### Create this 2D matrix:
##### array([[1., 1., 1., 1., 1.],
#####       [1., 1., 1., 1., 1.]])

In [50]:
np.ones((2, 5)) 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### Q5
##### Allocate an uninitialized block of memory for a (4, 3) array — the fastest possible allocation. You will fill every cell before reading it.
##### output
##### Goal: reserve uninitialized memory
##### shape: (4, 3)  |  dtype: float64
##### ⚡ Fastest allocation — no fill step
##### ⚠  You must overwrite every cell before reading!

In [51]:
np.empty((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Q6
##### Create this constant-filled 2D matrix:
##### array([[9, 9, 9],
#####       [9, 9, 9],
#####       [9, 9, 9]])

In [55]:
np.full((3,3) ,9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

#### Q7
###### Create this identity matrix:
##### array([[1., 0., 0., 0.],
#####       [0., 1., 0., 0.],
#####       [0., 0., 1., 0.],
#####       [0., 0., 0., 1.]])

In [56]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Q8
##### Create this array of exactly 5 evenly-spaced values:
##### array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [57]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### Q9
##### Create this evenly-spaced 1D array:
##### array([  0,   5,  10,  15,  20,  25])

In [58]:
np.arange(0,25,5)

array([ 0,  5, 10, 15, 20])

#### Q10
##### Create a random integer array of this shape with values in [1, 10). Your values will differ!
##### array([[4, 9, 2, 7, 1],
#####       [8, 5, 3, 6, 4]])

In [81]:
np.random.randint(1,10, size = (2,5), dtype=np.int64)

array([[8, 4, 2, 6, 6],
       [4, 6, 2, 2, 4]])